config/routes.rb
Rails.application.routes.draw do

  root 'demo_ctrl#home'

  get 'demo_ctrl/index'
  get 'demo_ctrl/home'
  get 'demo_ctrl/about'
  get 'demo_ctrl/contact'

  ## adding all resouseful routes 
  get 'menu' => 'access#menu'
  get 'login' => 'access#new'
  get'logout' => 'access#destroy'

  resource :access, controller: 'access', except: [:show, :edit, :update] do
    member do
      get :menu
    end
  end

  resources :subjects do 
    member do 
      get :delete
    end
  end

  resources :pages do 
    member do 
      get :delete
    end
  end


end

  # get 'pages/index'
  # get 'pages/show'
  # get 'pages/new'
  # get 'pages/edit'
  # get 'pages/delete'
  # get 'subjects/index'
  # get 'subjects/show'
  # get 'subjects/new'
  # get 'subjects/edit'
  # get 'subjects/delete'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # default route
  # get ':controller(/:action(/:id))'

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
    belongs_to :subject
end

app/models/subject.rb
class Subject < ApplicationRecord
    has_many :pages
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/access_controller.rb
class AccessController < ApplicationController

  before_action :confirm_login, :except => [:new, :create]


  # display menu
  def menu
    @user_id = session[:user_id]
  end

  # display login form
  def new
  end


  # process login form
  def create
    # do login process here
    logger.info("~~~~~~~ User #{params[:username]} logging in ~~~~~~~")
    cookies[:username] = params[:username]
    cookies[:lang] = 'en'
    session[:user_id] = 1122
    flash[:notice] = "Log in successful"
    redirect_to(menu_path)
  end

  # logout user
  def destroy
    logger.info("~~~~~~~ User #{session[:username]} logging out ~~~~~~~")
    session[:user_id] = nil
    flash[:notice] = "Log-out successful"
    redirect_to(login_path)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    layout "application"
    before_action :set_name_lang
    protect_from_forgery with: :exception


    protected

    def confirm_login
        if session[:user_id].present?
            return true
        else
            flash[:notice] = "Try login in"
            redirect_to(login_path)
        end
    end


    def set_name_lang
        @username = cookies[:username] if cookies[:username].present?
        @userlang = cookies[:lang] if cookies[:lang].present?
    end

    def render_404
        filepath = Rails.root.join('public', '404.html')
        render(file: filepath, status: 404, layout: false) and return
    end
end

app/controllers/demo_ctrl_controller.rb
class DemoCtrlController < ApplicationController
  before_action :confirm_login

  def index
    
  end

  def home
    red = "This is a var i used in home fro demop ctrl"
    @lol = "the lol instance "

    @myArray = [red, @lol]
  end

  def about
    render ('about_us')
  end

  def contact

    if ['us'].include?(params['country'])
      @phone = 'Usa phone'
    elsif params['country'] == 'ca'
      @phone = 'CA phone'
    else
      @phone = 'World phone'
    end

    render ('contact_us')
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_action :confirm_login

  def index
    @pages = Page.order('position ASC')
  end

  def show
    @page = Page.find(params[:id])
  end

  def new
    @page = Page.new
  end

  def create
    # Instantiate a new object using form parameters
    @page = Page.new(page_params)
    # Save the object
    if @page.save
      # If save succeeds, redirect to the index action
      flash[:notice] = 'Page created'
      redirect_to(pages_path)
    else
      # If save fails, redisplay the form so user can fix problems
      render('new')
    end
  end

  def edit
    @page = Page.find(params[:id])
  end

  def update
    @page = Page.find(params[:id])
    if @page.update(page_params)
      flash[:notice] = 'Page updated'
      redirect_to(page_path(@page))
    else
      render('edit')
    end
  end

  def delete
    @page = Page.find(params[:id])
  end

  def destroy
    @page = Page.find(params[:id])
    @page.destroy
    flash[:notice] = 'Page destroyed'
    redirect_to(pages_path)
  end

  private

    def page_params
      params.require(:page).permit(
        :name,
        :visible,
        :position,
        :permalink,
        :content,
        :subject_id
      )
    end

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController


  before_action :confirm_login

  def index

    @subjects = Subject.all

  end

  def show
    @subject = Subject.find(params[:id])
  end

  def new
    @subject = Subject.new(:visible => false, :position => 3) 
  end

   def create
    @subject = Subject.new(sub_prams)
     if @subject.save 
      flash[:notice] = "Subject Created"
      redirect_to (subjects_path)
     else 
      render('new')
     end
   end

  def edit
    @subject = Subject.find(params[:id])
  end

  def update
    @subject = Subject.find(params[:id])
    if @subject.update(sub_prams)
      flash[:notice] = "Subject Updated"
      redirect_to(subject_path(@subject))
    else 
      render('edit')
    end

  end

  def delete
    @subject = Subject.find(params[:id])
  end

  def destroy

    @subject = Subject.find(params[:id])
    flash[:notice] = "Subject Deleted"
    if @subject.destroy
      flash[:notice] = "Subject Deleted"
      redirect_to(subjects_path)
    end
  end
  
  private 

  def sub_prams
    
    params.require(:subject).permit(:visible, :name, :position)
    
  end
  


end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/application_helper.rb
module ApplicationHelper



    def status_tag(boolean, options={})
        options [:true_text]||= ''
        options [:false_text]||= ''
        if boolean 
            content_tag(:span, options[:true_text], :class=>'status true')
        else
            content_tag(:span, options[:fales_text], :class => 'status false')
        end
    end

end

app/helpers/demo_ctrl_helper.rb
module DemoCtrlHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/access/_flash.html.erb
 <% if flash[:notice].present?%>
<div class="alert alert-success" role="alert">
    FLASH NOTICE --
<%= flash[:notice] %>
</div>
<%end%>

app/views/access/_navbar.html.erb
 <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Home Page', root_path, class:"navbar-brand"%></li>  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">   <%= link_to 'Subjects', subjects_path, class:"nav-link"%></li>
      <li class="nav-item">   <%= link_to 'Pages', pages_path, class:"nav-link"%></li>
      <li class="nav-item">   
        <% if session[:user_id].present?%>
        <%= link_to image_tag('logo.png', size:'14x14', title:'logout') + " #{@username}", logout_path, class:"nav-link"%></li>
        <% else %> 
        <%= link_to 'Login',login_path , class:"nav-link"%></li>
        <% end %>
      </ul>

  </div>
</nav>
 <%= javascript_pack_tag 'hello_react' %>  

app/views/access/menu.html.erb
<%= render 'flash' %>

<h1>Access#menu</h1>
<p>you are loggged in as </p>
<%= @username %>
<%= @user_id %>

<%= link_to "loggout", logout_path, method: :delete %>

<div> 
<ul> 
<li> 
<%= link_to "Manage Subjects", subjects_path %>
</li>
<li> 
<%= link_to "Manage Page", pages_path %>
</li>
</ul> 
</div>

app/views/access/new.html.erb
<% content_for(:title) { 'Log In' } %>

<%= render 'flash' %>

<div class="access new">
  <h2>Welcome</h2>
  <p>A simulated log in form</p>


  <%= form_tag(access_path) do %>
    <table summary="login">
      <tr>
        <th><%= label_tag(:username) %></th>
        <td><%= text_field_tag(:username, params[:username]) %></td>
      </tr>
      <tr>
        <th><%= label_tag(:password) %></th>
        <td><%= password_field_tag(:password) %></td>
      </tr>
    </table>

    <div class="form-buttons">
      <%= submit_tag("Log In") %>
    </div>

  <% end %>
</div>

app/views/demo_ctrl/about_us.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About us</title>
</head>
<body>
    <p> We are all about Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta ea aliquid inventore, voluptate commodi explicabo blanditiis facere nulla recusandae qui deleniti iure iste corrupti totam eligendi cumque voluptas magnam suscipit!
    Non porro, minus aut, ea necessitatibus autem ipsa quasi excepturi ducimus expedita odit, molestiae est vel! Laboriosam in, impedit rem eius praesentium vitae ut ullam saepe veritatis voluptatem cum animi!</p>
    <br> 
    <p> we pride in Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quis veniam modi maxime. Sapiente eius excepturi nobis necessitatibus ducimus accusamus quibusdam perferendis ratione, dolorum nemo reiciendis aut maxime totam. Tenetur, ex.
    Dolorum aut optio distinctio, incidunt impedit suscipit quo eos cumque eligendi facere, ut temporibus sequi aliquid, accusamus expedita numquam! Atque numquam deserunt iusto sapiente explicabo modi unde ex magni iste!</p>
</body>
 <%= link_to "contact US", {:action=>'contact', :country=>'CA'} %>

</html>

app/views/demo_ctrl/contact_us.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact US</title>
</head>
<body>
    <h2> Contact us</h2>
    <p> 
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt beatae aut ipsa. Iusto deserunt accusamus esse error sapiente facilis ipsum quisquam saepe excepturi, veritatis sed dolor fugit minus fuga quaerat.
    </p>

    <% if params['country'].downcase  == 'us' %>
        Tel : USA num
        
    <% elsif params['country'].downcase  == 'ca'  %>
            Tel : CA num
    <% else %>
        Tel : World
    <% end %>
</body>
<%= link_to "About US", demo_ctrl_about_path %>
</html>

app/views/demo_ctrl/home.html.erb
<h1>
    Qasim Home
</h1>

<nav>
<%= link_to "About US", {:action=>'about'} %>

</nav>
<p>ERB</p>

<%  red1 = "This is a var page"%>

<% @myArray.each_index do |n| %>
<%= n+1 %>
<br>
<%="#{red1}!"%>
<br> 
<%= "#{@myArray}" %>
<br> 
<% end %>`

<%= link_to "Index Page", {:action => 'index', :param1=>'red', :param2 => "red"}%>

<%= link_to "edit sub 1", edit_subject_path(1) %>

<%= link_to "Login", login_path %>

<%= link_to "Just sub", subject_path(1) %>

app/views/demo_ctrl/index.html.erb
<h1>DemoCtrl#index</h1>
<p>Find me in app/views/demo_ctrl/index.html.erb</p>



Param : <%= params['param2']%> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ROR_LL<%= '-'+yield(:title) if content_for?(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
 <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
 <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>  <!-- NAVBAR -->
    <%= render 'access/navbar'%>
 
 
 
<div class="container">
    <%= yield %>
</div>
  </body>
 
</html>

app/views/pages/delete.html.erb
<h1>Pages#delete</h1>
<p>Find me in app/views/pages/delete.html.erb</p>

app/views/pages/edit.html.erb
<h1>Pages#edit</h1>
<p>Find me in app/views/pages/edit.html.erb</p>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/pages/new.html.erb
<h1>Pages#new</h1>
<p>Find me in app/views/pages/new.html.erb</p>

app/views/pages/show.html.erb
<%= link_to "Just sub", page_path(1) %>

app/views/subjects/_f.html.erb
<%= f.text_field (:name) %>
<% count = Subject.count%>
<%= f.text_field (:position) %>

<%= f.text_field(:visible) %>

app/views/subjects/delete.html.erb
<h1>Subjects#delete</h1>
<p>Find me in app/views/subjects/delete.html.erb</p>

<%= form_for(@subject, :method=> 'delete') do |f| %>
You sure 

<div class="form-buttons">
<%= f.submit("Delete Subject") %>
</div>
 <% end %>

app/views/subjects/edit.html.erb
<h1>Subjects#edit</h1>
<p>Find me in app/views/subjects/edit.html.erb</p>


<%= form_for( @subject) do |f| %>


<%= render :partial => "f", :locals=>{:f => f}  %>


<div class="form-button">

<%= f.submit("Create Subject") %>

</div>
<% end %>

app/views/subjects/index.html.erb
<h1>Subjects#index</h1>
<p>Find me in app/views/subjects/index.html.erb</p>

<%= link_to "Add a new Subject", new_subject_path, :class => 'action new' %>

<table class='table'>
    <tr>
        <th>ID</th>
        <th> Subject</th>
        <th>pages</th>
        <th>visible</th>
        <th>Actions</th>
    </tr>

<% @subjects.each do |subject| %>

<tr>

<td> <%=subject.id%>  </td>
<td> <%=subject.name %> </td>
<td> <%= pluralize(subject.pages.size, 'Page')%> </td>
<td> <%= status_tag(subject.visible) %> </td>
<td class = 'actions'>
<%= link_to "Show",  subject_path(subject), :class => "action show"%>
<%= link_to "Edit", edit_subject_path(subject), :class => 'action edit' %>
<%= link_to "delete", delete_subject_path(subject), :class => 'action delete' %>
</td>    </tr>
<% end %> 
</table>

app/views/subjects/new.html.erb
<h1>Subjects#new</h1>
<p>Find me in app/views/subjects/new.html.erb</p>


<%= form_for( @subject, :url => subjects_path ) do |f| %>

<%= render :partial => "f", :locals=>{:f => f}  %>

<div class="form-button">
<%= f.submit("Create Subject") %>
<% end %>

app/views/subjects/show.html.erb
<%= @subject.id %>
<%= link_to "Just sub", edit_subject_path(@subject.id) %>

  <tr> 
    <th><%= @subject.id %></th>
    <th><%= @subject.position ? '23': "dd dsss" %></th>
    <th><%= @subject.name %></th>
    <th><%= @subject.visible ? 'YES' : 'NO' %></th>
   
</table>